library: main.cpp book.cpp book.hpp category.cpp category.hpp bookpile.cpp bookpile.hpp bookbot.cpp bookbot.hpp bookdrop.cpp bookdrop.hpp storagepile.cpp storagepile.hpp
	g++ -std=c++03 -o library main.cpp book.cpp category.cpp bookpile.cpp bookbot.cpp bookdrop.cpp storagepile.cpp

test: test.cpp book.cpp book.hpp category.cpp category.hpp bookpile.cpp bookpile.hpp bookbot.cpp bookbot.hpp bookdrop.cpp bookdrop.hpp storagepile.cpp storagepile.hpp
	g++ -std=c++03 -o test test.cpp book.cpp category.cpp bookpile.cpp bookbot.cpp bookdrop.cpp storagepile.cpp
